"""Update id in table users from Integer to UUID

Revision ID: bbc49a9fe5d8
Revises: f581f20e50ca
Create Date: 2024-06-07 10:13:55.443217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbc49a9fe5d8'
down_revision: Union[str, None] = 'f581f20e50ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
